/**
 * Generates `src/environments/environment.production.ts` from the
 * `API_URL` environment variable (as set in Vercel / CI), falling back
 * to `http://localhost:3000` when the variable is absent.
 *
 * Run automatically before `ng build` (see package.json "build" script).
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const apiUrl = process.env.API_URL || process.env.apiUrl || 'http://localhost:3000';

const outDir = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'environments');
mkdirSync(outDir, { recursive: true });

const content = `/* Auto-generated by scripts/set-env.mjs — do not edit. */
export const environment = {
  production: true,
  apiUrl: '${apiUrl}',
};
`;

writeFileSync(join(outDir, 'environment.production.ts'), content);
console.log(`[set-env] API_URL -> ${apiUrl}`);
